Api
aykuli/dualboot-ror pull request #12
Opened 2022-10-20 16:52 UTC by aykuli

2022-10-28 17:49 UTC, greybutton requested changes

2022-10-28 17:49 UTC, greybutton commented on app/controllers/api/v1/application_controller.rb
> +class Api::V1 < Api::ApplicationController
Api::V1::ApplicationController

2022-10-28 17:49 UTC, greybutton commented on app/controllers/api/v1/tasks_controller.rb
> +class Api::V1::TasksController < Api::ApplicationController
< Api::V1::ApplicationController

2022-10-28 17:49 UTC, greybutton commented on app/controllers/application_controller.rb
> +  include AuthHelper
это лучше в апи, в теории могут быть еще неймспейсы, где авторизация не нужна

2022-10-28 17:49 UTC, greybutton commented on config/initializers/ams.rb
> +require 'active_model_serializers'
кажется это лишний файл

2022-10-28 17:49 UTC, greybutton commented on db/migrate/20221028154457_change_tasks_expired_at_type_from_date_to_datetime.rb
> +class ChangeTasksExpiredAtTypeFromDateToDatetime < ActiveRecord::Migration[6.1]
1 зачем эта миграция?
2 up обычно пишут вначале, потом down)
3 можно в одну строчку написать change_column :table, :field, :type

2022-10-28 17:49 UTC, greybutton commented on db/seeds.rb
> +Dir[File.join(Rails.root, "db", "seeds", "*.rb")].sort.each do |seed|
1 не очень понял смысл разделять сиды, только сложнее стал код) вот эти неуверенные find_or_create_by)
2 возможно require будет проще сделать

2022-10-29 04:46 UTC, aykuli commented on app/controllers/api/v1/application_controller.rb
> +class Api::V1 < Api::ApplicationController
got it

2022-10-29 04:46 UTC, aykuli commented on app/controllers/application_controller.rb
> +  include AuthHelper
got it

2022-10-29 11:03 UTC, aykuli commented on db/seeds.rb
> +Dir[File.join(Rails.root, "db", "seeds", "*.rb")].sort.each do |seed|
1 tasks, также, как и users сиды, явно, тут только для разработки (меня), чтобы видеть результат. На прод такое же не пойдет. `find_or_create_by` написан для того, чтобы, если захотелось добавить еще сидов для визуальной уверенности (тестирования) в правильной структуер приходящих данных по апи, добавить. А старые сиды не пересидировать. То есть не сбрасывать всю бд, а просто добавить сверху.
2 Почему-то с require не работает. Наверно поэтому появляются статьи подобно этому https://dev.to/eclecticcoding/rails-multiple-seed-files-3422 (в чате )

2022-10-29 11:03 UTC, aykuli commented on db/seeds.rb
> +Dir[File.join(Rails.root, "db", "seeds", "*.rb")].sort.each do |seed|
Поэтому я бы хотела это оставить.

2022-10-29 11:03 UTC, aykuli commented on db/migrate/20221028154457_change_tasks_expired_at_type_from_date_to_datetime.rb
> +class ChangeTasksExpiredAtTypeFromDateToDatetime < ActiveRecord::Migration[6.1]
Поэтому я хочу оставить эту миграцию.

2022-10-29 19:24 UTC, greybutton requested changes

2022-10-29 19:24 UTC, greybutton commented on config/initializers/ams.rb
> +require 'active_model_serializers'
файл config/active_model_serializer.rb перенести в initializers

файл config/initializers/ams.rb удалить

рут для разных экшенов может быть разный

2022-10-29 19:24 UTC, greybutton commented on db/seeds.rb
> +Dir[File.join(Rails.root, "db", "seeds", "*.rb")].sort.each do |seed|
> То есть не сбрасывать всю бд, а просто добавить сверху.

а проверяли, что второй вызов rails db:seed срабатывает после изменения сидов?

давай хотя бы тогда в users создавать юзеров, а не только админов. в таскс таски, а не юзеров и таски

2022-10-29 19:24 UTC, greybutton commented on db/migrate/20221028154457_change_tasks_expired_at_type_from_date_to_datetime.rb
> +class ChangeTasksExpiredAtTypeFromDateToDatetime < ActiveRecord::Migration[6.1]
хорошо

2022-10-30 16:42 UTC, aykuli commented on config/initializers/ams.rb
> +require 'active_model_serializers'
А! Спасибо! Нашла ошибку! Ошибка была в том, что ActiveModelSerializers было написано синуглярно. Shame on me!

2022-10-30 16:52 UTC, aykuli commented on db/seeds.rb
> +Dir[File.join(Rails.root, "db", "seeds", "*.rb")].sort.each do |seed|
я отрефакторила в один файл, и для тасков выбрала уже созданных менеджера и девелоперов.

## `Manager` and his `my_tasks`
![0](https://user-images.githubusercontent.com/49780822/198890944-345c6e83-421d-4d92-acc2-a2e2d08a7ab3.png)

## `Developer` first and his `assignee_tasks` 
![1](https://user-images.githubusercontent.com/49780822/198890949-47dce929-cee4-4752-a0c7-d4607497d9e0.png)

## `Developer` second and his `assignee_tasks` 
![2](https://user-images.githubusercontent.com/49780822/198890952-3f27929b-a76c-4293-8e89-7ce7f2a95bb1.png)

2022-10-30 19:44 UTC, greybutton approved these changes

2022-10-31 16:39 UTC, merged