Tasks handling
aykuli/dualboot-ror pull request #15
Opened 2022-11-02 16:20 UTC by aykuli

2022-11-06 11:53 UTC, greybutton requested changes
1 почему компоненты написаны в index файлах?
2 компоненты не в папке packs должны быть

2022-11-06 11:53 UTC, greybutton commented on app/controllers/api/v1/tasks_controller.rb
> +    render json: tasks, each_serializer: TaskSerializer, root: 'items', meta: build_meta(tasks)
почему render?

2022-11-06 11:53 UTC, greybutton commented on app/javascript/constants.js
> +export const SEVERITY = {
SEVERITY?) что это значит?)

2022-11-06 11:53 UTC, greybutton commented on app/javascript/forms/TaskForm/index.js
> +      expiredAt: task.expiredAt ? new Date(task.expiredAt).toISOString() : undefined,
почему так?

2022-11-06 11:53 UTC, greybutton commented on app/javascript/packs/components/AddPopup/index.js
> +import TaskForm from '../../../forms/TaskForm';
убрать относительные импорты на много уровней, пример `from 'forms/TaskForm';`

2022-11-06 11:53 UTC, greybutton commented on app/javascript/packs/components/AddPopup/index.js
> +      {isOpenSnakbar && message && <Snackbar isOpen={isOpenSnakbar} type={message.type} text={message.text} />}
1 опечатка
2 какой то неуверенный код. может быть так, что нужно открыть снакбар, но не будет сообщения?

2022-11-06 11:53 UTC, greybutton commented on app/javascript/packs/components/EditPopup/index.js
> +import Form from '../Form';
смешались пакетные и локальные импорты

2022-11-06 11:53 UTC, greybutton commented on app/javascript/packs/components/EditPopup/index.js
> +function EditPopup({ cardId, onClose, onDestroyCard, onLoadCard, onUpdateCard }) {
почему поменяла паттерн onEntityAction => onActionEntity?

2022-11-06 11:53 UTC, greybutton commented on app/javascript/packs/components/TaskBoard/index.js
> +      });
не понял зачем это, ниже все равно же релоад колонки есть, там все и обновится

2022-11-06 11:53 UTC, greybutton commented on app/javascript/repositories/TasksRepository.js
> +import { api_v1_tasks_path as apiV1TasksPath, api_v1_task_path as apiV1TaskPath } from '../routes/ApiRoutes';
по идее в роутах сразу должны быть функции в камелКейс

2022-11-06 11:53 UTC, greybutton commented on lib/tasks/js_routes.rake
> +    File.new(file_name, "w+") unless File.exists?(file_name)
это зачем?

2022-11-06 11:53 UTC, greybutton commented on utils/fetchHelper.js
> +import axios from 'axios';
этот файл в папке javascript

2022-11-06 11:53 UTC, greybutton commented on utils/keysConverter.js
> +import humps from 'humps';
этот тоже

2022-11-06 12:26 UTC, aykuli commented on app/javascript/constants.js
> +export const SEVERITY = {
Я думала, одна из популярных ui-бибилотек может служить как референс по best-practice, как надо называть пропсы для компонентов.

Референс: 

https://mui.com/material-ui/react-snackbar/#customization

![0](https://user-images.githubusercontent.com/49780822/200170573-899fbcd9-5bf1-4ebd-b667-5c560f1b713d.png)

2022-11-06 12:29 UTC, aykuli commented on app/javascript/forms/TaskForm/index.js
> +      expiredAt: task.expiredAt ? new Date(task.expiredAt).toISOString() : undefined,
а где это делать? на беке? input[type="date"] генерирует же строку дату, а не ISO формата

2022-11-06 12:34 UTC, aykuli commented on app/javascript/packs/components/EditPopup/index.js
> +function EditPopup({ cardId, onClose, onDestroyCard, onLoadCard, onUpdateCard }) {
Потому что до EditPopup был AddPopup. А там нейминг был написан  в стиле `onActionEntity`. Я просто продолжила ранее принятый паттерн.

![1](https://user-images.githubusercontent.com/49780822/200171021-e00c195b-8a8c-4511-ad36-085146b63fcd.png)

2022-11-06 12:46 UTC, aykuli commented on app/javascript/packs/components/TaskBoard/index.js
> +      });
да, ты прав, лишнее, спасибо.

2022-11-06 12:47 UTC, aykuli commented on utils/fetchHelper.js
> +import axios from 'axios';
да, точно!

2022-11-06 12:47 UTC, aykuli commented on utils/keysConverter.js
> +import humps from 'humps';
да, точно!

2022-11-06 13:00 UTC, aykuli commented on app/javascript/packs/components/EditPopup/index.js
> +import Form from '../Form';
ок, добавлю вертикальное разделение.

2022-11-06 13:45 UTC, aykuli commented on lib/tasks/js_routes.rake
> +    File.new(file_name, "w+") unless File.exists?(file_name)
![0](https://user-images.githubusercontent.com/49780822/200174371-ced39bd9-f9b5-4fbb-affd-b6709f40476c.png)

2022-11-06 16:33 UTC, aykuli commented on app/javascript/packs/components/AddPopup/index.js
> +import TaskForm from '../../../forms/TaskForm';
ок, приписала алиасы для вебпака

2022-11-06 16:33 UTC, aykuli commented on app/javascript/packs/components/AddPopup/index.js
> +      {isOpenSnakbar && message && <Snackbar isOpen={isOpenSnakbar} type={message.type} text={message.text} />}
да, действительно, спасибо!

2022-11-06 16:34 UTC, aykuli commented on app/javascript/repositories/TasksRepository.js
> +import { api_v1_tasks_path as apiV1TasksPath, api_v1_task_path as apiV1TaskPath } from '../routes/ApiRoutes';
да, вы правы, я их сгенерировала оказывается, без параметра `camel_case`, потом увидела, что не все соответствует в задании, а перекомпилировать не перекомпилировала.

2022-11-08 14:43 UTC, aykuli commented on app/controllers/api/v1/tasks_controller.rb
> +    render json: tasks, each_serializer: TaskSerializer, root: 'items', meta: build_meta(tasks)
там была ошибка, зазобрадась с `responders`, исправила, теперь работает.

2022-11-08 14:44 UTC, aykuli commented
> 1 почему компоненты написаны в index файлах?
> 2 компоненты не в папке packs должны быть

1 почему компоненты написаны в index файлах?
Я так видела делают, чтоб не создавать кучу файлов. Мне не принципиально, сделаю, как в dualboot.
2 компоненты не в папке packs должны быть
Переснесла и webpack компилятор перенастроила

2022-11-08 19:37 UTC, greybutton requested changes

2022-11-08 19:37 UTC, greybutton commented on app/controllers/api/v1/tasks_controller.rb
> +    respond_with(tasks, each_serializer: TaskSerializer, root: 'items', meta: build_meta(tasks), format: 'json')
зачем format?

2022-11-08 19:37 UTC, greybutton commented on app/controllers/api/v1/application_controller.rb
> +  respond_to :json
это уже есть в app/controllers/api/application_controller.rb

2022-11-08 19:37 UTC, greybutton commented on app/javascript/components/AddPopup/AddPopup.js
> +      {isOpenSnakbar && message && <Snackbar isOpen={isOpenSnakbar} type={message.type} text={message.text} />}
1 опечатка
2 какой то неуверенный код. может быть так, что нужно открыть снакбар, но не будет сообщения?

2022-11-08 19:37 UTC, greybutton commented on app/javascript/components/TaskBoard/TaskBoard.js
> +        Promise.all([loadColumn(destination.toColumnId), loadColumn(source.fromColumnId)]).then((res) => {
зачем это усложнение с Promise.all? было проще и понятней когда каждая колонка обновляется

2022-11-08 19:37 UTC, greybutton commented on app/javascript/components/TaskBoard/TaskBoard.js
> +      {isOpenSnakbar && <Snackbar isOpen={isOpenSnakbar} type={message?.type} text={message?.text} />}
здесь тоже не увереный код с вопросиками)

2022-11-08 19:37 UTC, greybutton commented on config/webpack/custom.js
> +const path = require('path');
без кастомизации вебпака не работает так же? по идее должно

2022-11-09 07:05 UTC, aykuli commented on app/controllers/api/v1/tasks_controller.rb
> +    respond_with(tasks, each_serializer: TaskSerializer, root: 'items', meta: build_meta(tasks), format: 'json')
cleaned up.

2022-11-09 07:06 UTC, aykuli commented on app/controllers/api/v1/application_controller.rb
> +  respond_to :json
true

2022-11-09 07:06 UTC, aykuli commented on app/javascript/components/AddPopup/AddPopup.js
> +      {isOpenSnakbar && message && <Snackbar isOpen={isOpenSnakbar} type={message.type} text={message.text} />}
fixed

2022-11-09 08:35 UTC, greybutton approved these changes

2022-11-09 08:35 UTC, greybutton commented on app/javascript/components/AddPopup/AddPopup.js
> +/* eslint-disable no-unused-vars */
почему правило линтера отключено? может убрать не используемые переменные?

2022-11-09 08:35 UTC, greybutton commented on app/javascript/components/TaskBoard/TaskBoard.js
> +      loadColumnInitial(key).then(() => (index === COLUMNS.length - 1 ? setIsUpdateBoard(true) : undefined)),
в жаваскрипте руками undefined никогда не стоит задавать, если нет какого то значения то null. Или можно так писать `index === COLUMNS.length - 1 && setIsUpdateBoard(true)`

2022-11-09 08:38 UTC, greybutton commented on app/javascript/components/TaskBoard/TaskBoard.js
> +        Promise.all([loadColumn(destination.toColumnId), loadColumn(source.fromColumnId)]).then((res) => {
можно было не заморачиваться по рендеру

2022-11-09 08:55 UTC, aykuli commented on app/javascript/components/TaskBoard/TaskBoard.js
> +        Promise.all([loadColumn(destination.toColumnId), loadColumn(source.fromColumnId)]).then((res) => {
не, выглядит не красиво, дергается, моргает, не люблю такое.

2022-11-09 08:56 UTC, aykuli commented on app/javascript/components/TaskBoard/TaskBoard.js
> +      loadColumnInitial(key).then(() => (index === COLUMNS.length - 1 ? setIsUpdateBoard(true) : undefined)),
yes! of cource! Where is my eyes!

2022-11-09 09:01 UTC, merged