Task assignee with react-select
aykuli/dualboot-ror pull request #16
Opened 2022-11-08 14:51 UTC by aykuli

2022-11-10 19:17 UTC, greybutton requested changes

2022-11-10 19:17 UTC, greybutton commented on app/javascript/components/ColumnHeader/ColumnHeader.js
> +          {!!totalCount && (
почему проверка по totalCount?

2022-11-10 19:17 UTC, greybutton commented on config/application.rb
> +    config.app_generators.scaffold_controller :responders_controller
зачем?

2022-11-10 19:17 UTC, greybutton commented on db/seeds.rb
> -end
почему удалено?

2022-11-10 19:17 UTC, greybutton commented on app/javascript/presenters/TaskPresenter.js
> +      return `${this.twoDigit(date)}/${this.twoDigit(month)}/${year}`;
может toLocaleDateString попробовать использовать?

2022-11-11 12:12 UTC, aykuli commented on app/javascript/components/ColumnHeader/ColumnHeader.js
> +          {!!totalCount && (
Потому что с бека отдается 0, если нет ничего. То и смысла показывать пагинации нету же.

2022-11-11 12:12 UTC, aykuli commented on config/application.rb
> +    config.app_generators.scaffold_controller :responders_controller
хм, похоже результат экспериментов. удалю.

2022-11-11 12:18 UTC, aykuli commented on app/javascript/components/ColumnHeader/ColumnHeader.js
> +          {!!totalCount && (
отрефакторила.

2022-11-11 12:18 UTC, aykuli commented on app/javascript/components/ColumnHeader/ColumnHeader.js
> +            ({cards.length}/{Number.isNaN(totalCount) ? '…' : totalCount})
refactored

2022-11-11 12:19 UTC, aykuli commented on db/seeds.rb
> -end
Потому что сейчас я могу создавать задачи через интерфейс.

В стадии разработки АПИ нужны были для проверки работоспособности ендпоинта. А сейчас это проверяется через клиентскую часть приложения.

2022-11-11 12:40 UTC, aykuli commented on app/javascript/presenters/TaskPresenter.js
> +      return `${this.twoDigit(date)}/${this.twoDigit(month)}/${year}`;
да, действильно, хороший метод для интерфейса. 
.
Оlнако инпут хочет формат только по документации (хотя странно, что для `toLocaleDateString` нет такого параметра как `dilimitter`), поэтому похоже придется использовать дополнительный метод для инпута. Странно, что он не кушает ISO date string:
![0](https://user-images.githubusercontent.com/49780822/201341996-9ad47c3a-68eb-4705-a351-6f484597805e.png)

2022-11-11 14:49 UTC, greybutton approved these changes

2022-11-11 15:19 UTC, merged