Redux and changed theme color
aykuli/dualboot-ror pull request #17
Opened 2022-11-10 17:45 UTC by aykuli

![8](https://user-images.githubusercontent.com/49780822/201168691-4d2678c9-845e-4c42-b20d-acb04fca5965.png)

2022-11-14 16:33 UTC, greybutton requested changes
1 AddPopup, EditPopup не надо было менять, у них такие же пропсы остаются
2 TaskBoard не перенесен в containers
3 почему `import useTasksActions from 'slices/useTasksActions';`? у нас же в примере не так
4 ui можно было оставить в таскбоард на локальном стейте
5 В целом, сложно сделано. Нужно было основные экшены убрать в редакс и данные, а получилось что переписали вообще все. Идея была в том, что редакс не так уж затратно добавить и не требует изменения большого количества кода

2022-11-15 14:57 UTC, aykuli commented
> 1 AddPopup, EditPopup не надо было менять, у них такие же пропсы остаются 
2 TaskBoard не перенесен в containers 
3 почему `import useTasksActions from 'slices/useTasksActions';`? у нас же в примере не так 
4 ui можно было оставить в таскбоард на локальном стейте 
5 В целом, сложно сделано. Нужно было основные экшены убрать в редакс и данные, а получилось что переписали вообще все. Идея была в том, что редакс не так уж затратно добавить и не требует изменения большого количества кода

1 Вернула
2 TaskBoard перенесла в containers
3 убрала 
4 убрала
5 убрала

2022-11-16 05:49 UTC, greybutton requested changes
не понял почему некоторые изменения удаляются, как будто уже в девелопе есть. некоторых файлов не хватает, например app/javascript/store.js

2022-11-16 05:49 UTC, greybutton commented on app/controllers/api/v1/tasks_controller.rb
> +    search.sorts = 'created_at desc'
сортировку не надо хардкодить в контроллере, она либо с фронта приходит, либо дефолт берется

2022-11-16 05:49 UTC, greybutton commented on app/javascript/containers/TaskBoard/TaskBoard.js
> +import { useTasksActions } from 'slices/TasksSlice';
слайс не импортируем напрямую в компонент, есть хук useTasks в него нужные функции и выборки стора убираем и оттуда используем в компонентах. например, board и loadBoard, с остальными функциями по аналогии

2022-11-18 12:27 UTC, aykuli commented
> не понял почему некоторые изменения удаляются, как будто уже в девелопе есть. некоторых файлов не хватает, например app/javascript/store.js

Я неправильно сделала с ветками, следующий МР был аппрунут, и я его смержила, а не надо было. Я ресетнула ветку develop на текущую позицию, смержу следующее аппрувнутой задание после этой, последовательно (как и создавала ветки для задании).

2022-11-18 17:05 UTC, greybutton approved these changes

2022-11-20 06:28 UTC, merged